---
# Sample command line play using EC2 inventory
# ansible -i /home/james/opt/ansible/plugins/inventory/ec2.py -m command -a ping all -u ec2-user --private-key=/home/james/Dropbox/AWSKeys/Sydney.pem
##



# file: aws-drupal.yml

- name: Install Drupal
  hosts: tag_Name_AnsibleTest4
  user: ec2-user
  gather_facts: True

  # Do some stuff on each instance ....

  tasks:
    - name: Ensure NTP is up and running
      action: service name=ntpd state=started
   
    - name: Install Apache Web Server
      action: yum pkg=httpd state=latest
      sudo: yes

  roles:
    - role: webtier
    - role: database
    - role: drush
    - role: drupal
