---
# Sample command line play using EC2 inventory
# ansible -i /home/james/opt/ansible/plugins/inventory/ec2.py -m command -a ping all -u ec2-user --private-key=/home/james/Dropbox/AWSKeys/Sydney.pem
##



# file: aws-drupal.yml
#
# Run this with ansible-playbook and supply the private key for your EC2/Euca user (to access the instance in the second play), e.g:
# ansible-playbook eucalyptus-ec2-deploy.yml -v --private-key=/path/to/ec2/pri/key


- name: Start instance
  hosts: local
  gather_facts: false

  vars:
    image: ami-a5bd2f9f
    instance_type: t1.micro
    keypair: Sydney
    security_group: Ansible
    zone: ap-southeast-2a
    region: ap-southeast-2
    instance_tags: '{"Name":"AnsibleTest"}'

  tasks:
    - name: Launch instance 
      local_action: ec2 keypair={{keypair}} group={{security_group}} instance_type={{instance_type}} image={{image}}
                    zone={{zone}} region={{region}} instance_tags='{"Name":"AnsibleTest4"}' ec2_access_key={{ec2_access_key}}
                    ec2_secret_key={{ec2_secret_key}} wait=yes count=1
      register: ec2

    - name: Wait for the instances to boot by checking the ssh port
      local_action: wait_for host={{item.public_dns_name}} port=22 delay=60 timeout=320 state=started
      with_items: ${ec2.instances}

    # Use the ec2_vol module to create volumes for attachment to each instance. Use with_items to attach to each instance (by returned id) launched previously.

#    - name: Create a volume and attach
#      local_action: ec2_vol volume_size=20 instance={{item.id}}
#      with_items: ${ec2.instances}

