---
# file: drushtest.yml
- hosts: local
  user: james
  sudo: yes


  vars_prompt:
    - name: "sitename"
      prompt: "Enter Site name"
      private: no
      default: "mydrupal"

    - name: "sitepass"
      prompt: "Enter the admin password for the new site"
      private: yes

  roles:
    - role: webtier
    - role: database
    - role: drush
    - role: drupal

