---
# file: Laptops.yml
- hosts: "{{hosts}}"
# remote_user: root **default
  sudo: yes
  roles:
    - role: DevLaptop
    - role: awsManager
    - role: ipython
    - role: btsync
#    - role: juju
    - role: nodejs
#    - role: minecraft #when: {{ ansible_hostname }}="carl"
#    - role: sublimetext #when: {{ ansible_userspace_bits }}="64"
