---
# file: Laptops.yml
- hosts: "{{hosts}}"
#  user: james
  roles:
    - role: DevLaptop
    - role: awsManager
    - role: ipython
#    - role: juju
    - role: nodejs
#    - role: minecraft #when: {{ ansible_hostname }}="carl"
#    - role: sublimetext #when: {{ ansible_userspace_bits }}="64"
