---
# file: nodejs/tasks/main.yml

- name: Add nodejs PPA
  apt_repository: repo='ppa:chris-lea/node.js'

- name: update repository cache
  apt: update_cache=yes
  tags: nodejs

- name: Install Node 
  apt: pkg={{ item }} state=present
  with_items:
  - nodejs
  tags: nodejs

# sudo npm install -g yo grunt-cli bower
- name: NPM install Yoman, Grunt, Bower and Mongojs
  npm: name={{ item }} state=present global=yes
  with_items:
  - yo
  - grunt-cli
  - bower
  - mongojs
  tags: npm

# sudo npm install -g DOCPAD version 6.59
- name: NPM install DOCPAD v6.59
  npm: name=docpad version=6.59 state=present global=yes
  tags: npm
