---
# file: ansible/tasks/main.yml


- name: install requiried packages (*buntu)
  apt: pkg={{ item }} state=installed
  with_items:
  - git
  - aptitude
  - python-yaml
  - python-jinja2
   
  #debug: msg="Dummy entry. needs to be replaced."
  tags: ansible

- name: Download Ansible from git
  git: repo=https://github.com/ansible/ansible.git
       dest=/home/james/opt/ansible
       version=release1.4.0
  #sudo_user: james
  tags: ansible
  
- name: fix permissions on opt/ansible
  file: path=/home/james/opt/ansible owner=james group=james state=directory recurse=yes

- name: Copy over my Ansible .bash_alias backing up original
  copy: src=myAnsible.bash_alias dest=/home/james/.bash_aliases backup=yes
  tags: ansible
